name: adminbeauty
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  logger: ^2.5.0
  http: ^1.3.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.0
  another_flushbar: ^1.10.0
  intl: ^0.17.0
  flutter_hooks: ^0.18.0 # Thay đổi phiên bản nếu cần
  image_picker: ^0.8.4+4 # Thay đổi phiên bản nếu cần
  toast: ^0.3.0
  provider: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  async: ^2.13.0
  material_color_utilities: ^0.12.0
  fake_async: ^1.3.3
  leak_tracker: ^10.0.9
  vm_service: ^15.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo.png
    - lib/assets/loginadmin.jpg
    - lib/assets/fogot-icon.png